# Generated by Django 4.2.6 on 2023-11-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_cateagory_options_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateagory',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
