# Generated by Django 4.2.6 on 2023-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features')),
                ('icon', models.FileField(upload_to='features')),
                ('icon_background', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('testimonial_description', models.TextField()),
                ('testimonial_author', models.CharField(max_length=225)),
                ('author_desigination', models.CharField(max_length=225)),
                ('testimonial_logo', models.FileField(upload_to='features')),
            ],
            options={
                'db_table': 'web_feature',
                'ordering': [-1],
            },
        ),
    ]
