# Generated by Django 4.2.6 on 2023-10-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={},
        ),
    ]
