# Generated by Django 4.2.6 on 2023-10-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_videoblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial/images')),
                ('logo', models.FileField(blank=True, null=True, upload_to='testimonial/logo')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=128)),
                ('desigination', models.CharField(max_length=128)),
                ('Company_name', models.CharField(max_length=128)),
                ('is_fetutured', models.BooleanField()),
            ],
            options={
                'db_table': 'web_testimonial',
                'ordering': ['-id'],
            },
        ),
    ]
