# Generated by Django 4.2.6 on 2023-10-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='Company_name',
            new_name='company_name',
        ),
    ]
