# Generated by Django 4.2.6 on 2023-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_color',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
