# Generated by Django 4.2.6 on 2023-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_product_button_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_color',
            field=models.CharField(max_length=128),
        ),
    ]
