# Generated by Django 4.2.6 on 2023-10-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_product_button_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog')),
                ('title', models.CharField(max_length=128)),
                ('content_type', models.CharField(choices=[('Blog Post', 'Blog Post'), ('Webinar', 'Webinar'), ('Report', 'Report')], max_length=128)),
            ],
        ),
    ]
