# Generated by Django 4.2.6 on 2023-10-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='blog',
            table='web_blog',
        ),
    ]
