# Generated by Django 4.2.6 on 2023-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_blog_options_alter_blog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='button_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
