# Generated by Django 4.2.6 on 2023-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_blog_button_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='button_name',
            field=models.CharField(max_length=128),
        ),
    ]
