# Generated by Django 4.2.6 on 2023-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_blog_button_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_type',
            field=models.CharField(choices=[('blog_post', 'Blog Post'), ('webinar', 'Webinar'), ('report', 'Report')], max_length=128),
        ),
    ]
