# Generated by Django 4.2.6 on 2023-10-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_blog_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('company_size', models.CharField(choices=[('1', '1-10'), ('2', '11-50'), ('3', '51-200'), ('4', '201-500')], max_length=128)),
                ('industry', models.CharField(choices=[('1', 'Agriculture'), ('2', 'Banking & Finance'), ('3', 'Business Services & Software')], max_length=128)),
                ('job_role', models.CharField(choices=[('1', 'C-Suite'), ('2', 'VP')], max_length=128)),
                ('country', models.CharField(choices=[('us', 'United States'), ('afghanistan', 'Afghanistan'), ('albania', 'Albania')], max_length=128)),
                ('user_agrement', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'web_contact',
                'ordering': ['-id'],
            },
        ),
    ]
