# Generated by Django 4.2.6 on 2023-10-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='white_image',
            field=models.FileField(blank=True, null=True, upload_to='customers'),
        ),
    ]
