# Generated by Django 4.2.6 on 2023-10-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_customer_white_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(default='a', upload_to='product/hero_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Studio', max_length=128),
            preserve_default=False,
        ),
    ]
