# Generated by Django 4.2.5 on 2023-09-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_promoter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('faq_type', models.CharField(choices=[('rent_tracking', 'Rent Tracking'), ('new_deposit', 'New Deposit'), ('existing_deposit', 'Existing Deposit')], max_length=125)),
            ],
        ),
    ]
